
jwt:
  secret: EF87h5ZES5By6MRIqdOpsE3D4W2-sPFpjg3INCOhFDZi-w462RqhFB3g3BOfLl1T3kN8C-84BxrgD8bWX6MZ6w
  lifetime: 60m

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: postgres
  application:
    name: spring-security
server:
  port: 8080

